algorithm_name: degree-collector
algorithm_type: exact
server_address: 127.0.0.1:9090
worker_config:
  num_workers: 3
  worker_id: worker-0
  vertex_assignment:
    '0': worker-0
    '1': worker-1
    '2': worker-2
    '3': worker-0
    '4': worker-1
    '5': worker-2
    '6': worker-0
    '7': worker-1
    '8': worker-2
    '9': worker-0
    '10': worker-1
    '11': worker-2
    '12': worker-0
    '13': worker-1
    '14': worker-2
    '15': worker-0
    '16': worker-1
    '17': worker-2
    '18': worker-0
    '19': worker-1
graph_config:
  format: edgelist
  local_testing: true
  file_path: data
  directed: false
parameters:
  num_rounds: 2
